	<div id="footer" style="border:2px solid; margin-top: 4em; padding: 1em;">
		<p>Ein Projekt f&uuml;r RDB WS 2015/16 &mdash; Erstellt mit <strong>PHP</strong> <?=phpversion()?> &amp; <strong>MySQL</strong> <?=$sql->getAttribute(PDO::ATTR_SERVER_VERSION)?></p>
		<p>Von Britta Walter Matr. Nr. 2171031</p>
		<!--<img src="img_5375" alt="eine grafik" > sieht nicht so top aus hier-->
	</div>
</body>
</html>